apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
