apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args: ['http-server', '--proxy', 'http://34.65.119.146:8080?', 'dist']
          image: web:latest
          name: web
          ports:
            - containerPort: 8080
      restartPolicy: Always
